version: '3'

# Carregando variáveis de ambiente
dotenv:
  - .env

# Ativando modo silencioso
silent: true

# Definindo variáveis gerais
vars:
  APP_PATH_BUILD: "./cmd/baseapi"
  VERSION:
    sh: git describe --always --tags

# Definições de tarefas
tasks:
  # Tarefa padrão
  default:
    deps: [build]
    cmds:
      - ./baseapi.exe

  # Tarefa para configuração de produção
  prod:
    cmds:
      - ./baseapi.exe

  # Tarefa para configuração local
  local:
    deps: [build]
    env:
      SERVER_ADDR: 0.0.0.0:7788
      SERVER_ALLOW_REGISTER: true

      # Database
      DATABASE_HOST: localhost
      DATABASE_PORT: 27017
      DATABASE_USER: baseapi
      DATABASE_PASS: baseapi
      DATABASE_NAME: baseapiMM
      DATABASE_MECH: SCRAM-SHA-1

      # JWT
      JWT_SECRET: baseapi

    cmds:
      - |
        # Executar a aplicação
        ./baseapi.exe

  # Compila a aplicação para um executável
  build:
    cmds:
      - go build -o baseapi.exe -ldflags="-X 'github.com/marlonlorram/baseapi.Version={{.VERSION}}'" {{.APP_PATH_BUILD}}
